### ISSUE TITLE
后台用户处理中与用户处理完毕数据有差异

### ISSUE THREAD

**Issue by zhengmenjing** [JoleneOL/cash-dating#17]
用户处理中是用户还为协议签章的，而用户处理完毕数据是用户已经签章的，这2个目前状态均是签章和其他，需要区分开来，如果用户处理中状态应该显示未签章，用户处理完毕数据里面显示已签章

**Comment by caijiang** [comment]
建议再跑一次本流程；可能跟之前的投融家提供错误的合同号有关。

**Comment by xiaofenYou** [comment]
流程我跑了一遍 依旧存在问题

**Comment by caijiang** [comment]
会在下版本中修复
