### ISSUE TITLE
合伙人与发展人三个主要修改问题

### ISSUE THREAD

**Issue by xiaofenYou** [JoleneOL/cash-dating#26]
1.普通用户发展用户5个以上费率调档，没有自动降档。
2.款爷后台无法查询所谓发展人发展的普通用户消费记录问题
3.款爷后台订单查询界面应区分最终受益人，或者权属归谁，涉及到谁从谁属.

**Comment by caijiang** [comment]
1. 这个跟 #24 是一样的

1. 已修复

1. 目前没有人也最终受益人之说。

所以我决定关闭该issue.
