### ISSUE TITLE
在款爷后台添加类似报表菜单

### ISSUE THREAD

**Issue by xiaofenYou** [JoleneOL/cash-dating#29]
报表包含用户名、用户电话、支付日期、到账日期、交易笔数、交易金额、手续费率、手续费金额、支付通道等

**Comment by caijiang** [comment]
用于做什么的？是谁在看这份报表？

**Comment by xiaofenYou** [comment]
我们后台管理员可见 用于每笔订单可清晰与投融家核对

**Comment by caijiang** [comment]
...................

**Comment by xiaofenYou** [comment]
后台管理可否添加初步审核审核未通过人员名单，方便查找人员信息及向对方反馈信息问题

**Comment by caijiang** [comment]
这个关闭了 去 #31 讨论

**Comment by zhengmenjing** [comment]
这个报表是与收银台和二维码收款有关的数据表格

**Comment by caijiang** [comment]
如果是这样请在 #22 里说明；
