### ISSUE TITLE
项目贷款需要详细数据可以导出来

### ISSUE THREAD

**Issue by zhengmenjing** [JoleneOL/cash-dating#31]
项目贷款全部菜单中，所需要与投融核对的数据有：用户申请时间   申请人姓名   申请人身份证号码   申请人电话    借款金额   产品期限   款爷审核时间   投融家审核时间    审核人   审核状态  备注

**Comment by caijiang** [comment]
投融家审核时间-

**Comment by zhengmenjing** [comment]
1：用户申请时间（例如2016.12.22  11：13模式）：可查询筛选每日，每周，每月，每年                                    2：借款金额（目前就一个金额20万）：可查询10万  20万                                                                                                           3：产品期限：30天 ， 90天                                                                                                                                       4：审核人：尤晓芬，  叶德雷  ，郑门静                                                                                                                           5：审核状态：款爷审核结果（包含通过和不通过），  投融家审核结果（包含通过和不通过） ， 未签章，   已签章                                                                                                                                                                 6：备注：身份证信息审核不通过   申请人是失信被执行人

**Comment by caijiang** [comment]
我没看太懂，我还是按照我自己理解的模式去做吧。

**Comment by caijiang** [comment]
@zhengmenjing 导出格式有什么要求?office excel?

**Comment by zhengmenjing** [comment]
excel表格形式导出

**Comment by caijiang** [comment]
产品期限存在2个； 1 是申请时的 2 是初审通过是的确定值； 报表中应该出现哪个？ 已经作为筛选条件 它依据的又是哪一个

**Comment by caijiang** [comment]
除了报表结果；相关疑问也存在在 「项目贷款」列表页面；

**Comment by xiaofenYou** [comment]
客户提交180天，我们初审显示30天，提交显示30天，投融家那边显示30天，客户那边显示30天

**Comment by caijiang** [comment]
> 产品期限存在2个； 1 是申请时的 2 是初审通过是的确定值； 报表中应该出现哪个？ 已经作为筛选条件 它依据的又是哪一个

仔细看我说的……

**Comment by xiaofenYou** [comment]
应该出现在2 申请和初审通过的确定值应该统一

**Comment by caijiang** [comment]
- 申请时的期限
- 我方点击同意的期限 这个值是和投融家收到的一致的

**Comment by xiaofenYou** [comment]
我懂你的意思了  也就是说这跟我们这边无关 与投融家那边审批期限有关
