### ISSUE TITLE
后台管理项目贷款表格补充

### ISSUE THREAD

**Issue by xiaofenYou** [JoleneOL/cash-dating#33]
1、过滤掉重复提交资料人数。据统计，导出表哥人数与实际提交人数不符，有包括重复提交人
2、对手误通过的申请资料可直接驳回，避免供应商的审核麻烦
3、希望在显示资料里添加身份证号显示，方便审核人复制到网页上查询法院被执行信息，以及与照片对号。

**Comment by caijiang** [comment]
1. 这个还不行，比如出现重复的一个人的2个资料，请问我应该过滤掉哪个？

1. 是指可以驳回处于任意阶段的申请么?

1. 没问题

**Comment by xiaofenYou** [comment]
1、那这个问题我自己用记录来解决
2、是的 就是在初审后、供应商终审后这两个阶段对用户执行驳回
3、谢谢

**Comment by caijiang** [comment]
Q2 处理中。

**Comment by xiaofenYou** [comment]
我经常有用户申请通过不了的情况，每次点击同意就说禁止访问

**Comment by caijiang** [comment]
「禁止访问」这个问题目前我还没有了解具体原因；再次在发生的时候 你可以通过即时聊天工具 分享案例；我可以立即检查这个案例 以了解具体原因。

**Comment by xiaofenYou** [comment]
好的
