### ISSUE TITLE
微信订单支付成功通知：

### ISSUE THREAD

**Issue by aizi031** [JoleneOL/cash-dating#39]
商品名称：无
这个需要改成具体的商品名称。

**Comment by caijiang** [comment]
什么是“微信订单支付成功通知”？
没有开发过此项通知；

说下具体收到通知的场景和通知的标题。

**Comment by aizi031** [comment]
这个不能上传图片，已经和叶德雷沟通，让他写在测试文档里了

**Comment by caijiang** [comment]
我刚通知叶德雷 让他把issue丢这边管理； 💃
