### ISSUE TITLE
特卖问题汇总

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#40]
1. 待付款中，点击付款后应出现对应付款详情页。
2.已支付成功后的券，名称是“星巴克大杯券”，把“星巴克8折优惠券，1.00元优惠券”去掉。
3.已使用的券，点开后的页面也需要和“第2点”一样进行修改。，还需要去掉那串字母。
4.支付成功后的券，商品要默认收货。
5.确认支付时，把“未知商品”改为“星巴克大杯优惠券”。
6.确认使用时，不需要弹框提示“使用时像商家出示此二维码”。
7.订单支付成功通知中，商品名称没有显示，订单编号最好用数字编号。
8.选择购买数量时，无需弹框提示最少数量为1.
9.购买时，点击上半部分应不可以滑动，遮盖层应该消失。数量处应无法点击数字输入弹框，增加
+，-的点击区域。合计处算法显示有问题。

**Comment by caijiang** [comment]
too big to manage.
