### ISSUE TITLE
分享的链接，内容应可以调整

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#60]
分享出去的链接，”标题“，”图片“，”内容“都应可以调整。

**Comment by aizi031** [comment]
转发可以自己编辑标题和内容：但发送好友时，好友打开时“服务正在升级中”

**Comment by caijiang** [comment]
好友打开时的URL 发一个

**Comment by aizi031** [comment]
http://app.kuanyes.com/cash/sale/goodsDetail?_inviteBy=5&from=singlemessage
