### ISSUE TITLE
上传的星巴克二维码要识别全部

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#65]
上传的星巴克二维码需要识别全部内容。
![fullsizerender 44](https://cloud.githubusercontent.com/assets/25718181/23248058/6964e6f4-f9d8-11e6-8b78-4f91e93dd70a.jpg)

**Comment by caijiang** [comment]
不行的原因……………………省略5000个关于技术解释的字…………

就是不行
