### ISSUE TITLE
款爷借款需要增加一个圆梦贷款。

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#67]
款爷借款需要增加一个圆梦贷款，只需要链接到第三方网站，不需要提供任何其他功能。春爱已上传资料。需要尽快上线。

**Comment by caijiang** [comment]
@aizi031  没有发现已提交的commit包含此项修改;若是我未找到 可否附加commit id?

**Comment by deleiye** [comment]
commit ID：bd16c3780f4f245dafd95d382f666232a41bccdf [bd16c37]
浏览地址：https://joleneol.github.io/cash-dating/web/src/main/webapp/loanmain.html
