### ISSUE TITLE
套现217 P1

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/cash-dating#7]
* 合伙人从其团队中获取手续费优惠的收益降低到0%
* 合伙人不再具备修改团队手续费率的功能
* 任意用户邀请了5个有效用户之后 即可获得「优惠手续费率」

**先完成核心功能，无视商务方向**

**Comment by xiaofenYou** [comment]
那就是手续费在合伙人邀请人数满5个有效用户后自动降档手续费吗，不可手动
