### ISSUE TITLE
“我的订单”里面内容显示错误

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#70]
“我的订单”里面应该只显示“特卖”中的商品购买订单。“资金流水”中显示所有资金交易订单。

**Comment by JoleneOL** [comment]
假定我的订单只显示商城订单；那么商城里面的我的订单应该显示什么？
难不成直接把链接换成商城里面的我的订单？
而且这个改动将导致用户再也无法追逐套现进度；三思而行啊；

**Comment by deleiye** [comment]
我的订单就只显示特卖订单，特卖中的我的订单也要显示。
套现进度可在资金流水中查看进度。资金流水显示的是全部的资金交易。

**Comment by JoleneOL** [comment]
？？那删除（我的订单）是否就解决问题了？

**Comment by deleiye** [comment]
不是的，二个订单现在都要存在。就是现在有二个地方能查看到特卖商品购买的订单。
款爷中心的我的订单按照春爱姐发的界面来制作。

**Comment by caijiang** [comment]
我并不介意在页面上加入一个链接。
我介意的是缺少了功能。

资金流水看的是资金，「当前我的订单」界面是用于让用户管理套现方面的订单，如果尚未到账资金流水就无法管理；

为什么不选择增加一个到「商城-我的订单」的链接解决流量引入商城的问题呢？

**Comment by deleiye** [comment]
可在“资金流水”中显示套现进度，如显示“收款中”，“收款成功”。
