### ISSUE TITLE
新优惠特卖图片上传后显示变形

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#75]
![0b52cf7a-a629-18e2-1452-f0105a674f24](https://cloud.githubusercontent.com/assets/25718181/24396164/d1fb9e4a-13d4-11e7-87e7-7a6e889afbf7.png)
![d744ea33-ca72-07ef-f09f-ddda647d8dbc](https://cloud.githubusercontent.com/assets/25718181/24396276/29555b4a-13d5-11e7-892e-31a23f204901.png)

**Comment by caijiang** [comment]
图片尺寸规格，请参考春爱提供的标准。

**Comment by deleiye** [comment]
首页展示图片能否不默认为商品详情页中的第一张图片。因为新优惠特卖中首页图片为长方形，详情页图片为正方形，导致变形。

**Comment by caijiang** [comment]
你跟春爱协商解决方案即可。

首先春爱需要就商城前端所支持的图片格式规范做出【明确说明】；并且前端可以完美支持「说明」中支持的规范。

其次我会按照【说明】修改商品管理后台，禁止不符合规范的图片进入系统。
或者作为高级解决方案：智能的截取，置空图片以保证符合【说明】的规范。

**Comment by deleiye** [comment]
1、首页banner轮播展位尺寸：2000*600
2、新优惠特卖4张图片展示尺寸：560*251
3、产品详情页产品5张轮播图尺寸：500*500

**Comment by caijiang** [comment]
可修改图片名称
在新品展示区域只显示名为「新品图片」的图片
同时在商品详情页面，将不再展示【新品图片】的图片

**Comment by caijiang** [comment]
准确的说图片名称包含【新品图片】的
