### ISSUE TITLE
支付手续费

### ISSUE THREAD

**Issue by xiaofenYou** [JoleneOL/cash-dating#8]
支付手续费由收款方承担，但我们的收款金额页面（温馨提示）写由付款方支付，此处有疑问

**Comment by caijiang** [comment]
呃，这个我让产品follow一下；最好你可以提供一些页面链接 补充下这个issue.

**Comment by caijiang** [comment]
@xiaofenYou 请update 下 该问题的状态;

**Comment by xiaofenYou** [comment]
现在收银台服务不稳定 页面时不时改变支付通道 等页面稳定下来我再测试 更新状态
