### ISSUE TITLE
pc商城支付时收款方显示混乱

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/cash-dating#80]
有的显示 重庆惟明惟识科技有限公司，有的显示福建生活运动电子商务公司，也有的显示我们之前的民生银行。能否统一显示民生银行，或者直接显示款爷盈家。

照片突然传不上去了。

**Comment by caijiang** [comment]
不可以

这是取决于我们的付款供应商「畅捷支付」正在使用的上行通道
